name: client_page
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.17
  image_picker: ^1.0.7
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  intl: ^0.18.1
  cached_network_image: ^3.4.1
  skeletonizer: ^1.0.0
  shimmer: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.12.0
  path_provider: ^2.1.1
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.svg"
  flutter_lints: ^5.0.0
  cached_network_image: ^3.4.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/Client_icont.svg
    - assets/icons/logo.png

